--customers who have spent over 100

SELECT C.CUSTOMER_ID,
	CONCAT (C.FIRST_NAME,' ',C.LAST_NAME), SUM(P.AMOUNT) AS TOTAL_SPENT
FROM CUSTOMER C
JOIN PAYMENT P ON C.CUSTOMER_ID = P.CUSTOMER_ID
GROUP BY 1,2
HAVING SUM(P.AMOUNT) > 100
ORDER BY TOTAL_SPENT DESC
